### ISSUE TITLE
Problema al usasr npm run dev

### ISSUE THREAD

**Issue by redBaron23** [frlp-utn-ingsoft/filmster#20]
Hola antes me andaba bien, pero recientemente cambie de disco y clone todo de nuevo de mi repo y al tirar npm run dev me tira esto

> filmster@1.0.0 dev /home/redbaron/myBuilds/filmster
> node ./server/src/fixture.js && nodemon ./server/src/index.js

internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'sequelize'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/redbaron/myBuilds/filmster/server/src/models/movie.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filmster@1.0.0 dev: `node ./server/src/fixture.js && nodemon ./server/src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the filmster@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/redbaron/.npm/_logs/2019-04-30T01_25_42_426Z-debug.log
![error](https://user-images.githubusercontent.com/23110463/56936509-1afb6100-6ace-11e9-869b-626f988b785c.png)

**Comment by redBaron23** [comment]
Me habia olvidado del npm install, saludos
